import axios from 'axios'

const API_URL = import.meta.env.VITE_API_BASE_URL || "http://localhost:8000/api";

const api = axios.create({
  baseURL: API_URL,
  withCredentials: true
})

//req Interceptor :auto-inject access token 
api.interceptors.request.use((config) => {
  /* As we are injecting the token in the config authHeader,
  we need to access it from localStorage  */
  const token = localStorage.getItem('token')
  if (token) {
    config.headers.Authorization = `Bearer ${token}`
  }
  return config //now config is updated with injected token
})

//res Interceptor :handle 401 and refresh acces token if expired 
api.interceptors.response.use(
  //if token not exppired , directly return the response
  (response) => {
    return response.data
  },

  //if error occours,go to this functionality
  async (error) => {
    /*here originaRequest is like we tried to call api/getJobs and failed
    whereas error.config is that request api/getjobs
    so we strored that failed request in the originalRequest so that
    when we will get a new token , we will retry the same request
    and the user wont feel any server crash */

    const originalRequest = error.config;

    if (error.response?.status === 401 && !originalRequest._retry) {
      originalRequest._retry = true
      /* This original request don't understand the error So it tries to
      access the Request again and again But we put that request is equal
      to true so that it understands that we have tried once and we can't
        fix that error so First fix the error and then come and reach to this Api */

      try {
        console.log('Token Expired..attempting refresh new Access Token');

        const res = await api.post('/auth/token/refresh', {})

        //update the old token with new access token
        const { newAccessToken } = res;

        //store the new token
        localStorage.setItem('token', newAccessToken)

        //inject new bearer Access Token
        originalRequest.headers['Authorization'] = `Bearer ${newAccessToken}`

        return api(originalRequest)
      } catch (e) {
        console.log(e);
        //if suppose server cant generate new access token
        localStorage.removeItem('token')

        //and return the user to login
        window.location.href = '/login';

        //and say that the error is not 401 ,and unable to fix it
        return Promise.reject(e);
      }
    }
    return Promise.reject(error); //error is except 401
  })


// --- Authentication ---

export async function loginUser(email, password) {
  const data = await api.post('/auth/login/', { email, password });
  /* This accessToken is the token sent by the login Controller
  but the new newAcessToken is generated by the token/refresh */
  if (data.accessToken) {
    localStorage.setItem("token", data.accessToken);
  }
  return data;
}

export async function signupUser({ username, email, password }) {
  return api.post('/auth/signup/', { username, email, password });
}

export async function verifyEmail(token) {
  return api.post(`/auth/verify/${token}/`);
}

export async function forgotPassword(email) {
  return api.post('/auth/forgot-password/', { email });
}

export async function resetPassword(token, password) {
  return api.post('/auth/reset-password/', { token, password });
}

// --- Jobs ---

export async function getJobs(query, page = 1, limit = 10) {
  return api.get('/jobs/jobs/', {
    params: { q: query, page, limit }
  });
}

// --- Profiles ---

export async function getProfileList() {
  return api.get('/userProfile/profile/');
}

export async function getProfile(id) {
  return api.get(`/userProfile/profile/${id}/`);
}

export async function createProfile(data) {
  return api.post('/userProfile/profile/', data);
}

export async function updateProfile(id, data) {
  return api.put(`/userProfile/profile/${id}/`, data);
}

export async function deleteProfile(id) {
  return api.delete(`/userProfile/profile/${id}/`);
}

// --- Resume ---

export async function uploadResume(file) {
  const formData = new FormData();
  formData.append("resume", file);

  return api.post('/resumeUpload/resume/upload/', formData, {
    headers: { 'Content-Type': 'multipart/form-data' }
  });
}

export default api;
